### ISSUE TITLE
Error during install of Isoviewer

### ISSUE THREAD

**Issue by PUW149** [KopfLab/isoviewer#30]
Installation of isoviewer from Github according to the instructions fails with "Error in eval(exprs[i], envir) : object '%OR%' not found"
R version is 4.1.0, devtools and rtools are installed, isoreader and isoprocessor all installed OK.
Any ideas?
Best wishes,
Simon

**Comment by sebkopf** [comment]
hi @PUW149, the `%OR%` function was previously provided by another package but we removed this dependency in the latest version of isoviewer, please reinstall the package and see if it fixes the issue you're seeing: `devtools::install_github("isoverse/isoviewer")`

**Comment by PUW149** [comment]
All good, install runs no problem.
thanks!
